#!/bin/bash

hostAndPort='localhost:4567'
stationID=''

echo "Running GETClient"

if [ $# -gt 0 ]; then
    if [ $# -gt 1 ]; then
        if [ ! -z $1 ]; then
            hostAndPort=$1
            echo "Host/Port: ${hostAndPort}"
        fi

        if [ ! -z $2 ]; then
            stationID=$2
            echo "StationID: ${stationID}"
        fi
    else
        stationID=$1
            echo "StationID: ${stationID}"
    fi
fi
    
echo "====================="
java -cp dest build.GETClient ${hostAndPort} ${stationID}